### ISSUE TITLE
Permission error on GITHUB_OUTPUT Still present

### ISSUE THREAD

**Issue by gthomson31** [github/stale-repos#101]
Hi there

We have just tried to re-run the stale-repos action since the recent changes and have found the GITHUB_OUTPUT error is still present. 

This issue was previously raised in #98 

```yaml
name: Stale Repositories Report Testing

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stale-repos:
    name: Stale repository report
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run stale_repos tool
        uses: github/stale-repos@v1
        env:
          GH_TOKEN: ${{ secrets.GH_STALE_REPO_KEY }}
          ORGANIZATION: <ORG_NAME>
          INACTIVE_DAYS: 365

```

Example of the error 
```shell
Found 65 stale repos in <ORG_NAME>
Traceback (most recent call last):
  File "/action/workspace/stale_repos.py", line 300, in <module>
    main()
  File "/action/workspace/stale_repos.py", line 57, in main
    output_to_json(inactive_repos)
  File "/action/workspace/stale_repos.py", line 244, in output_to_json
    with open(os.environ["GITHUB_OUTPUT"], "a") as file_handle:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/github/file_commands/set_output_f12c6469-3d43-4461-970d-03daabda9118'
```

**Comment by gthomson31** [comment]
@samuel-bland Adding for visibility

**Comment by jmeridth** [comment]
@gthomson31 confirmed this is still happening.  I believe it is because we will never have permissions to write to `$GITHUB_OUTPUT` as a file.  We can echo to it.  I'm going to try that and see what happens. @zkoppert you may have more insight into `$GITHUB_OUTPUT` permissions.

**Comment by zkoppert** [comment]
☝ Agree with you that we should use the documented path of echoing to it.

**Comment by jmeridth** [comment]
@zkoppert my confusion is now related to this was possibly working in [v1.10.0](https://github.com/github/stale-repos/blob/ba2f48608511e08dc66c06f52de85c7690cde5c1/stale_repos.py#L242) ([comment](https://github.com/github/stale-repos/issues/98#issuecomment-1995062518)).  Tested this is failing for me in v1.10.0 also when stale repos are detected.

@gthomson31 could you please change your stale-repos actions to use:

`uses: github/stale-repos@v1.10.0`

again and see if it worked when stale-repos were detected?  Thank you.

**Comment by jmeridth** [comment]
I'm working on this

**Comment by jmeridth** [comment]
Well that's very noisy. Sorry 🙇  Trying to shorten my dev cycle with live GitHub Action testing.


#### **TLDR**

**My suggestion**: rollback the changes in the Dockerfile where we specify a non-root user.


#### Details/Update:

So it seems we're in a losing battle by [setting a non-root user in the Dockerfile](https://github.com/github/stale-repos/blob/86b2df9df7c32a05abf15e2cc5dbf65433f674db/Dockerfile#L24).

[And the GitHub docs state, we will be if we keep the non-root user](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#administrative-privileges:~:text=Note%3A%20GitHub%20Actions%20must%20be%20run%20by%20the%20default%20Docker%20user%20(root).%20Ensure%20your%20Dockerfile%20does%20not%20set%20the%20USER%20instruction%2C%20otherwise%20you%20will%20not%20be%20able%20to%20access%20GITHUB_WORKSPACE.).

Without root we will never have write access to `$GITHUB_OUTPUT` environment variable.  That environment variable is a file path (example: `$GITHUB_OUTPUT` = `/home/runner/work/_temp/_runner_file_commands/set_output_76785449-caa5-4203-9a7e-2b774d621734` from one of my manual test runs)

/cc @zkoppert I'm going to put up a PR to go back to root user

**Comment by gthomson31** [comment]
Sorry just seen the github/stale-repos@v1.10.0 comment had tried on this also but faced the same issue

**Comment by jmeridth** [comment]
@gthomson31 thank you for confirming.

**Comment by jmeridth** [comment]
@gthomson31 I've tested and it is working for me again.  I await your feedback.  Cheers.

**Comment by gthomson31** [comment]
perfect - have just tested and working again now
