### ISSUE TITLE
New feature: integration with Slack/Discord

### ISSUE THREAD

**Issue by zkoppert** [github/stale-repos#15]
Instead of creating a github issue, could we put an example of an action workflow where it sends a slack or discord message to a given channel?

**Comment by navhits** [comment]
Check this official action by slack.

https://github.com/slackapi/slack-github-action

Usage of JSON output is documented in this repo's readme [here](https://github.com/github/stale-repos#using-json-instead-of-markdown)

Rest is up to your creativity 😁
