### ISSUE TITLE
How to run the workflow against private repositories within organization

### ISSUE THREAD

**Issue by shahmanthan1209** [github/stale-repos#17]
Hi team,
Can you please advise on how to run the GitHub action against the private repositories?

**Comment by ahatzz11** [comment]
I would also like to do this! The `GH_TOKEN` that I am passing is a Personal Access Token that has read/write to every repository in our organization, but it seems to only be grabbing public repos. I ran a report with `INACTIVE_DAYS: 1` and only got a few dozen repos - I expected close to 500 from our private organization.

**Comment by ahatzz11** [comment]
I did a little research on this, and it seems like a little oversight in the 3rd party GitHub python library that was chosen:

Some docs about the current method being used: https://github3.readthedocs.io/en/latest/api-reference/github.html#github3.github.GitHub.repositories_by

> List public repositories for the specified username.

Based on some [other docs](https://stackoverflow.com/questions/61005506/python-script-to-get-all-private-repos-from-an-org-user) (which are 3 years old, and the github3.py lib seems to kinda have some unclear documentation around this), it seems like this line:

```python
for repo in github_connection.repositories_by(organization):
```

Should be replaced with:
```python
org = github_connection.organization(organization)
for repo in org.repositories():
```

I'm definitely not a python expert so the above might not be 100% correct, but I think the `repositories_by(organization)` method call is the root of this issue.

**Comment by zkoppert** [comment]
👋🏻 Hi @shahmanthan1209 and @ahatzz11, That looks correct to me so I ran a quick test and it does in fact grab the private repos as long as the token has permission. When I designed this, I had in mind that this would be for public repos but no reason it couldn't be used internally as well! 

I'll open up a PR and tag you all on it.

**Comment by zkoppert** [comment]
This is now released in `v.1.1.0`. 🎉
