### ISSUE TITLE
Add additional information to created issue

### ISSUE THREAD

**Issue by ahatzz11** [github/stale-repos#20]
It would be awesome to see some additional metrics in the generated report! Here's a list of ideas, days since:

- Last Release
- Last PR made

Having these be configurable, with something like the following would be awesome:

```yaml
DAYS_INACTIVE_METRICS: 'push, release, pr'
```

**Comment by navhits** [comment]
@ahatzz11, what other actions can you think of?

**Comment by AlexanderLanin** [comment]
Less interesting for open source, but for enterprise organizations it would be nice to print the owner and the last n people who have pushed.

Potentially even creating an individual issue per stale repository (in the action repo / in the inactive repo), assigned to the owner of that repository.
