### ISSUE TITLE
Action is not certified by GitHub

### ISSUE THREAD

**Issue by ahatzz11** [github/stale-repos#25]
I noticed in the [marketplace](https://github.com/marketplace/actions/stale-repos) that this action is verified by the creator org of `github`, but it isn't considered certified by GitHub: 

![image](https://github.com/github/stale-repos/assets/6256032/5d2769cb-42e4-498c-ab89-2770294233fa)
![image](https://github.com/github/stale-repos/assets/6256032/2939c0bc-6123-4b40-9dbb-8b599009c18a)

Compare this to something like the [checkout](https://github.com/marketplace/actions/checkout) action and notice that it doesn't have the disclaimer. I'm not sure how certain actions get certified by GitHub, but I think this action should get marked as such. Maybe another good reason to have it live in `actions/`?

**Comment by camchenry** [comment]
@ahatzz11 I took a look into this, it looks like we show that message: "[action name] is not certified by GitHub ..." whenever the repository owner is not named `actions`:

https://github.com/github/github/blob/7d7f8e14793f4f237ace805cb7083d3314a67e94/app/views/marketplace/actions/_sidebar.html.erb#L85

It looks like the repository for the action is [`github/stale-repos`](https://github.com/github/stale-repos), which is not owned by `actions`, hence why this message appears. I suppose there is a good argument to be made for also supporting `github` as an owner, but for consistency maybe the action should be transferred to the `actions` org.
