### ISSUE TITLE
Needs an excessively privileged GH_TOKEN to run

### ISSUE THREAD

**Issue by bfabio** [github/stale-repos#39]
`GH_TOKEN` is required and the documentation states "_The GitHub Token used to scan repositories. Must have read and write access to all repositories_".

That's a lot of power (and also a lot of responsibility) - especially for a reporting tool - and in case of a compromise in the action, it's game over for orgs using it.

Is there a way around it?

**Comment by hopkinsth** [comment]
The documentation seems inaccurate here.

I'm running this tool using a GitHub App for authentication. I granted that App read-only access to repository contents, and this stale-repos works fine with those permissions. You could set up similar permissions using a fine-grained personal access token, but I would recommend avoiding classic PATs with this tool if you want to limit its write access to your repositories.
