### ISSUE TITLE
Add last push date to markdown and JSON outputs

### ISSUE THREAD

**Issue by navhits** [github/stale-repos#48]
The addition of the last push date for each repo to the output files will be helpful. Having an absolute date is more helpful compared to the relative number of days. 

Markdown

| Repository URL | Days Inactive | Last Push Date |
| --- | --- | ---: |
| https://github.com/example/repo1 | 5 | 2023-06-14 |

JSON
`{"url": "https://github.com/example/repo1", "daysInactive": 5, "lastPushDate": "2013-06-14"}`

**Comment by Zaid-maker** [comment]
> I have these changes done already in my fork. If the maintainers think this is a good enhancement. I can go ahead and raise a PR -> [main...navhits:stale-repos:main](https://github.com/github/stale-repos/compare/main...navhits:stale-repos:main)

I guess you should make PR lol

**Comment by zkoppert** [comment]
@navhits Yes, please open a pull request!
