### ISSUE TITLE
Request that a new minor version be published

### ISSUE THREAD

**Issue by anovadox** [github/stale-repos#81]
Trying to use the [enhancement](https://github.com/github/stale-repos/pull/79) I added, finding that even pointing the `uses` directly at the commit, I wasn't seeing the intended behavior:
```
    - name: Run stale_repos tool
      uses: github/stale-repos@5699b2bdeeb93744edade0d6fc9b73b1d811c0bc
      id: stale_repos
        GH_TOKEN: ${{ secrets.GH_RO_TOKEN }}
        EXEMPT_TOPICS: "keep,template"
        INACTIVE_DAYS: 365
        ACTIVITY_METHOD: "wrong"
```

This should have raised an exception in my calling workflow, but it kept on behaving like it did prior to the recent changes.

It looks like actions was pulling the container:
```
Pull down action image 'ghcr.io/github/stale_repos:v1'
  /usr/bin/docker pull ghcr.io/github/stale_repos:v1
  ...
  Digest: sha256:7944ed7c3bbf99a92f5400dfa691c3eb6bf2a5a8f72d80eb71a70d43c26128d7
```
Which I believe corresponds to the [version released in November](https://github.com/github/stale-repos/pkgs/container/stale_repos)

Thank you for your help!

**Comment by zkoppert** [comment]
Working on it! Thanks for the reminder. :)

**Comment by zkoppert** [comment]
Released: 
- https://github.com/github/stale-repos/releases/tag/v1.8.0
- https://github.com/github/stale-repos/pkgs/container/stale_repos
