### ISSUE TITLE
After triggering the flow, where do i see output file

### ISSUE THREAD

**Issue by sompesai** [github/stale-repos#86]
Hi,

Thanks for the workflow for stale repos validation. 
Success in triggering the workflow through Github actions, and viewed the count of stale repos in workflow jobs (events). Is there any other way i can view output of these runs. As it's written some output.md file, from where do i need to check that and how.

Thanks
Sai kumar

**Comment by zkoppert** [comment]
This action doesn't have an output.md file generated. The output would all be in the action log. https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/using-workflow-run-logs
