### ISSUE TITLE
[Feature Request] Allow GitHub App Installation Token instead of user PAT Token

### ISSUE THREAD

**Issue by jmeridth** [github/stale-repos#89]
To ensure the GitHub action is not dependent on a single user's PAT Token, I'd like to add functionality to allow for a GitHub App Installation Token.  ~This may require a switch from github3.py though.  I wasn't seeing it as an option with github3.py (still looking).~ github3.py handles app authentication, will stick with the same lib 😄 

> a GitHub App Installation Token is an efficient way to unlock the maximum alotted API calls to avoid rate limiting and can be used by multiple members of your organization

from [Community Discussions](https://github.com/orgs/community/discussions/48186#:~:text=a%20GitHub%20App%20Installation%20Token%20is%20an%20efficient%20way%20to%20unlock%20the%20maximum%20alotted%20API%20calls%20to%20avoid%20rate%20limiting%20and%20can%20be%20used%20by%20multiple%20members%20of%20your%20organization)

~[PyGitHub](https://github.com/PyGithub/PyGithub) is what I've used in the past.~

[GitHub App Installation Authentication](https://pygithub.readthedocs.io/en/stable/examples/Authentication.html#app-installation-authentication)

**Comment by jmeridth** [comment]
I'm willing to work on this one if fits in scope of project

**Comment by zkoppert** [comment]
Definitely in scope and users would benefit from getting the max number of allowable API calls especially for large organizations. Thanks for bringing up and volunteering!
