### ISSUE TITLE
Permission error on GITHUB_OUTPUT

### ISSUE THREAD

**Issue by bingenito** [github/stale-repos#98]
Great action that has been very helpful.  This has been successfully running for me until today where I'm getting an error on every run as it attempts to output the results.

```
  File "/action/workspace/stale_repos.py", line 244, in output_to_json
    with open(os.environ["GITHUB_OUTPUT"], "a") as file_handle:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/github/file_commands/set_output_1d3c5bca-ce94-4929-8268-f3e1653919d2'
```

I've tried recreating classic tokens (even with every permission enabled) or fine grained with no luck.  I've also tried the workflow on a different org and even a personal repository to make sure it wasn't related to organization settings that might have changed.  There is very little on GITHUB_OUTPUT and permissions, so I suspect this should simply work out of the box. I've also specified older releases of the action to verify it wasn't the latest release.

**Comment by bingenito** [comment]
Looks like all releases will now pull down the v1 of the docker image https://github.com/github/stale-repos/pkgs/container/stale_repos.  Could this be from the change to run as user instead of root?

**Comment by bingenito** [comment]
Confirmed working if I use older image directly - docker://ghcr.io/github/stale_repos:v1.10.0

**Comment by jmeridth** [comment]
@bingenito I experienced the same error.  Thank you for filing the issue.  I've submitted #99 for a fix.  Cheers.
